[project]
name = "csi-wekafs"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dagger-io",
    "pip>=25.1.1",
]

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[tool.uv.sources]
dagger-io = { path = "sdk", editable = true }
