# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: New features
      labels:
        - breaking
    - title: Improvements
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - fix
