#!/usr/bin/env bash
set -euo pipefail

# supressing ugly logs/unsetting OTEL
unset OTEL_EXPORTER_OTLP_ENDPOINT ANTHROPIC_API_KEY
export DAGGER_NO_NAG=1

export _EXPERIMENTAL_DAGGER_RUNNER_HOST='kube-pod://dagger-dagger-helm-engine-p42gm?namespace=infra'

exec dagger "$@"

