#syntax=docker/dockerfile:1.17
ARG UBI_HASH=9.7-1770267347
FROM registry.access.redhat.com/ubi9-minimal:${UBI_HASH} AS base

LABEL maintainers="WekaIO, LTD"
LABEL description="Weka CSI Metrics Server"
LABEL maintainer="csi@weka.io"
LABEL name="WEKA CSI Metrics Server"
LABEL vendor="weka.io"
LABEL summary="This image is used by WEKA CSI Metrics Server"
LABEL description="Metrics Server for WEKA CSI Volumes"
LABEL url="https://www.weka.io"

EXPOSE 2049 111/tcp 111/udp
ENTRYPOINT ["/metricsserver"]

RUN microdnf install -y util-linux libselinux-utils pciutils binutils jq procps less container-selinux
RUN microdnf clean all && rm -rf /var/cache/dnf

FROM base
ARG TARGETARCH
ARG TARGETOS
RUN mkdir -p /licenses
COPY LICENSE /licenses
COPY --chmod=755 ./build/${TARGETOS}-${TARGETARCH}/metricsserver /metricsserver

