ARG UBI_HASH=9.5-1736404036
ARG TARGETARCH
ARG TARGETOS
ARG VERSION
ARG LOCAR_VERSION=0.4.3

FROM registry.access.redhat.com/ubi9/ubi:${UBI_HASH}
RUN dnf install -y util-linux libselinux-utils pciutils binutils jq procps less container-selinux
RUN dnf clean all && rm -rf /var/cache/dnf

LABEL maintainers="WekaIO, LTD"
LABEL description="Weka CSI Driver"
LABEL maintainer="csi@weka.io"
LABEL name="WEKA CSI Plugin"
LABEL vendor="weka.io"
LABEL summary="This image is used by WEKA CSI Plugin and incorporates both Controller and Node modules"
LABEL description="Container Storage Interface (CSI) plugin for WEKA - the data platform for AI"
LABEL url="https://www.weka.io"
RUN mkdir -p /licenses
COPY LICENSE /licenses

ARG binary=/bin/wekafsplugin
EXPOSE 2049 111/tcp 111/udp
ENTRYPOINT ["/wekafsplugin"]

RUN curl -sSL -o /locar https://github.com/weka/locar/releases/download/${LOCAR_VERSION}/locar-${LOCAR_VERSION}-${TARGETOS}-${TARGETARCH} && \
    chmod 655 /locar
COPY --chmod=755 --from=plugin wekafsplugin /wekafsplugin
