kind: Pod
apiVersion: v1
metadata:
  name: csi-app-readonly-api
spec:
  # make sure that pod is scheduled only on node having weka CSI node running
  nodeSelector:
    topology.csi.weka.io/global: "true"
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
        readOnly: true
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo `date` hello >> /data/temp.txt; sleep 10;done"]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: pvc-wekafs-dir-readonly-api # defined in pvc-wekafs-dir.yaml
