kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wekafs-dir-api
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storageclass-wekafs-dir-api
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
