# Default values for metricsserver.
# -- Name of the driver (and provisioner)
csiDriverName: "csi.weka.io"

image:
  repository: images.scalar.dev.weka.io:5002/csi-metricsserver
  pullPolicy: Always
  tag: ""
imagePullSecret: ""

hostNetwork: false
metricsServer:
  # -- Number of replicas for metrics server
  replicas: 2
  # -- optional nodeSelector for metrics server only
  nodeSelector: {}
  # -- optional affinity for metrics server only
  affinity: {}
  # -- optional labels to add to metrics server deployment
  labels: {}
  # -- optional labels to add to metrics server pods
  podLabels: {}
  # -- tolerations for metrics server only
  tolerations: {}
  # -- concurrent requests for WEKA metrics
  maxConcurrentRequests: 20
  # -- metrics fetch interval in seconds, default is 300 seconds (every 5 minutes)
  metricsFetchIntervalSeconds: 300
  # -- termination grace period for metrics server pods
  terminationGracePeriodSeconds: 10
  # -- enable leader election for metrics server
  enableLeaderElection: true
  # -- number of concurrent requests for metrics server to update quota lists for a whole filesystem
  quotaUpdateConcurrentRequests: 10
  # -- the time period for which quotaMap of a certain filesystem should be considered valid. usually should match metricsFetchIntervalSeconds,
  #    but in deployments with thousands of PVCs this can be increased to reduce the load on the metrics server.
  #    Metrics in such case will be updated less frequently. But for each metric, a last update time will be recorded
  quotaMapValiditySeconds: 300

# -- Log level of CSI plugin
logLevel: 6
# -- Use JSON structured logging instead of human-readable logging format (for exporting logs to structured log parser)
useJsonLogging: false

metrics:
  # -- Enable Prometheus Metrics
  enabled: true
  # -- Metrics server metrics port
  metricsServerPort: 9096
# @ignore
tracingUrl: ""
# @ignore
tracingDeploymentIdentifier: ""

pluginConfig:
  allowInsecureHttps: false

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 0.1
    memory: 100Mi
