{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-node
    component: {{ .Release.Name }}-node
    release: {{ .Release.Name }}
    {{- with .Values.metrics.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node
      component: {{ .Release.Name }}-node
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.podMonitor.interval }}
{{- end }}
{{- end }}
