apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wekafs-dir-static-api
spec:
  storageClassName: storageclass-wekafs-dir-static-api
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  csi:
    driver: csi.weka.io
    # volumeHandle must be formatted as following:
    # dir/v1/<FILE_SYSTEM_NAME>/<INNER_PATH_IN_FILESYSTEM>
    # The path must exist, otherwise publish request will fail
    volumeHandle: dir/v1/testfs/testdir
    nodePublishSecretRef:
      name: csi-wekafs-api-secret
      namespace: csi-wekafs
    controllerExpandSecretRef:
      name: csi-wekafs-api-secret
      namespace: csi-wekafs
  # make PV schedulable only on nodes with WEKA CSI Plugin and healthy WEKA Client
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.weka-infra.weka.io/accessible
              operator: In
              values:
                - "true"
