{
 "title": "Weka CSI metrics server statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "value_max_age", "label": "Max age of values", "query": "1m,3m,5m,10m,15m,20m,25m,30m" },
   {
    "name": "pod",
    "label": "monitorserver pod",
    "query": {
     "query": "label_values(weka_csi_metricsserver_quota_cache_validity_seconds,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sum of URL requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(url) (weka_csi_api_request_count{pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Latency (mean)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(url) (rate(weka_csi_api_request_duration_seconds_sum{pod=\"$pod\"}[$__rate_interval])) / sum by(url) (rate(weka_csi_api_request_duration_seconds_count{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(url)(rate(weka_csi_api_request_count{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(url) (rate(weka_csi_api_request_duration_seconds_sum{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(weka_csi_api_request_duration_seconds_sum{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Number of PV capacities reported, by lookback window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(count_over_time(weka_csi_volume_pv_reported_capacity_bytes{pod=\"$pod\"}[$value_max_age]))\n",
     "legendFormat": "From PV spec ($value_max_age)"
    },
    {
     "expr": "count(count_over_time(weka_csi_volume_used_bytes{pod=\"$pod\"}[$value_max_age]))\n",
     "legendFormat": "From WEKA Stats ($value_max_age)"
    },
    {
     "expr": "count(count_over_time(weka_csi_volume_used_bytes{pod=\"$pod\"}[30m]))\n",
     "legendFormat": "From WEKA Stats (30m)"
    },
    {
     "expr": "count(count_over_time(weka_csi_volume_used_bytes{pod=\"$pod\"}[10m]))\n",
     "legendFormat": "From WEKA Stats (10m)"
    }
   ]
  },
  {
   "title": "Persistent Volumes added/removed from monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum without(pod) (weka_csi_metricsserver_pv_removals_count_total{pod=\"$pod\"})",
     "legendFormat": "PVs removed"
    },
    {
     "expr": "sum without(pod) (weka_csi_metricsserver_pv_additions_count_total{pod=\"$pod\"})",
     "legendFormat": "PVs added (Might lag)"
    }
   ]
  }
 ]
}