apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metricsserver.fullname" . }}
  labels:
    {{- include "metricsserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metricsserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metricsserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/csi-metricsserver"]
        env:
        - name: CSI_DRIVER_NAME
          value: {{ .Values.csiDriverName | quote }}
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}