# only if metricsServer.enabled is true and the metricsServerPort is set and Prometheus stack is installed
{{- if .Values.metricsServer.enabled }}
{{- if .Values.metrics.metricsServerPort }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-metrics-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-metrics-server
    component: {{ .Release.Name }}-metrics-server
spec:
    selector:
        matchLabels:
        app: {{ .Release.Name }}-metrics-server
        component: {{ .Release.Name }}-metrics-server
    namespaceSelector:
        matchNames:
        - {{ .Release.Namespace }}
    podMetricsEndpoints:
        - port: metrics
          metricRelabelings:
            - action: labeldrop
              regex: ^job$
            - action: labeldrop
              regex: ^instance$
            - action: labeldrop
              regex: ^namespace$
            - action: labeldrop
              regex: ^endpoint$
            - action: labeldrop
              regex: ^container$

{{- end }}
{{- end }}
{{- end }}
