apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-metrics-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-metrics-server
    component: {{ .Release.Name }}-metrics-server
    release: {{ .Release.Name }}
