kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wekafs-fs-mountoptions
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: storageclass-wekafs-fs-mountoptions
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
