apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wekafs-fssnap-static-api
spec:
  storageClassName: storageclass-wekafs-fssnap-static-api
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  csi:
    driver: csi.weka.io
    # volumeHandle must be formatted as following:
    # weka/v2/<FILE_SYSTEM_NAME>:<SNAPSHOT_ACCESS_POINT>[/innerPath]
    # Snapshot name must be csivol-<SNAPSHOT_ACCESS_POINT>
    # The path must exist, otherwise publish request will fail
    volumeHandle: weka/v2/testfs:testfs-2
    nodePublishSecretRef:
      name: csi-wekafs-api-secret
      namespace: csi-wekafs
    controllerExpandSecretRef:
      name: csi-wekafs-api-secret
      namespace: csi-wekafs
  # make PV schedulable only on nodes with WEKA CSI Plugin and healthy WEKA Client
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.weka-infra.weka.io/accessible
              operator: In
              values:
                - "true"
