kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wekafs-fs-snapshot-encrypted-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storageclass-wekafs-fs-encrypted-api
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: VolumeSnapshot
    name: snapshot-pvc-wekafs-fs-encrypted-api
    apiGroup: snapshot.storage.k8s.io
